### ISSUE TITLE
Ensure all Info Cards for all Commands are present 

### ISSUE THREAD

**Issue by seanlowjk** [AY1920S1-CS2103T-F13-2/main#194]
Currently, we have 28 commands as of today. 

We will need to complete the info cards for all 28 commands asap! 

Here are the completed and uncompleted info cards. 

- [X] Add
- [x] AutoSort
- [X] Budget
- [X] Buy
- [X] Clear
- [X] Collapse
- [x] CustomSort
- [X] Default
- [X] Delete
- [x] Dislike 
- [X] Edit
- [X] Exit
- [x] Expand
- [X] Filter
- [X] Find
- [X] Help
- [x] History
- [X] Info
- [x] Like
- [X] List
- [x] MakeSort
- [X] Recommend
- [x] RemoveDislike
- [x] RemoveLike
- [x] RemovePreference
- [X] Save
- [X] Sort
- [x] TopUp

**Comment by robytanama** [comment]
I will do `History`, `Collapse`, `Expand`, `Dislike`, and `Like`.

You guys can do the rest, or I don't mind doing everything so that the language is consistent. What do you guys think @Raikonen @fatclarence @jon-chua @seanlowjk?

**Comment by fatclarence** [comment]
@robytanama we finish this by today before v1.3.1 release since this is quite a repetitive task for now. removelike and removedislike I'll do. Then the rest can split amongst the rest. Then Roby at the end, you just double check our language. Then I think we are good to go for part 1 of product release.

**Comment by seanlowjk** [comment]
Added Info Cards for 

`MakeSort`
`CustomSort`
`AutoSort`

Reference to #193

**Comment by robytanama** [comment]
Added all the `Info` cards and updated the old ones in PR #209

**Comment by seanlowjk** [comment]
Done and closed.
