### ISSUE TITLE
As a user, I would wish to be able to add my savings of the month into a savings account

### ISSUE THREAD

**Issue by robytanama** [AY1920S1-CS2103T-F13-2/main#3]
so that I can track how much I have saved and manage my expenditure more wisely.

**Comment by fatclarence** [comment]
We should be focusing on this at a higher priority since this can actually encourage users to save up their money and encourage savings by users! I'll be assigning this to myself and will work closely with @Raikonen  to implement this.

**Comment by fatclarence** [comment]
Fixed #186 #177 #150 #132
