### ISSUE TITLE
Refactor AddressBook to $aveNUS

### ISSUE THREAD

**Issue by seanlowjk** [AY1920S1-CS2103T-F13-2/main#81]
Making sure that AddressBook fields and features are replace with those to better suit our project.

**Comment by seanlowjk** [comment]
Changes Made so far: 

Phone to Price: #75 
Email to Description: #77 #79
Category: #78 
Opening Hours: #80
Restrictions: #80

**Comment by fatclarence** [comment]
Completed this and reviewed by Ze Yuan :) Yay!
